version: '3.10'

services:

 backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:5973714m@db:5432/postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./backend:/app
    command: uvicorn src.srv:app --reload --host 0.0.0.0 --port 5000

 frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

 db:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5973714m
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
 postgres_data:
